blank_issues_enabled: false
contact_links:
  - name: ì´ìŠˆ ë°œí–‰
    url: https://github.com/hyezoprk/hyezoEditor/issues/new?template=issue_template.md
    about: If you've already asked for help with a problem and confirmed something is broken, create a issue report.
  - name: ì§ˆë¬¸
    url: https://github.com/hyezoprk/hyezoEditor/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
  - name: ê¸°ëŠ¥ ìš”ì²­
    url: https://github.com/hyezoprk/hyezoEditor/discussions/new?category=ideas
    about: 'Suggest any ideas you have using our discussion forums.'
  - name: ì•„ë¬´ë§
    url: https://github.com/hyezoprk/hyezoEditor/discussions/new?category=%EB%8B%A4%EC%A0%95%ED%95%9C-%EB%A7%90
    about: 'Anything you want to say to me ğŸ˜›'
